--
DELETE FROM `command` WHERE `name` IN ('tournament', 'tournament create', 'tournament delete', 'tournament state', 'tournament ilvl',
'tournament status', 'tournament standings', 'tournament dungeon', 'tournament dungeon set', 'tournament dungeon remove',
'tournament team', 'tournament team create', 'tournament team delete', 'tournament team info', 'tournament team list',
'tournament team disqualify', 'tournament team requalify', 'tournament team member', 'tournament team member add',
'tournament team member remove', 'tournament run', 'tournament run list', 'tournament run live', 'tournament run start',
'tournament run reject', 'tournament run void');
INSERT INTO `command` (`name`, `help`) VALUES
('tournament', 'Syntax: .tournament $subcommand\nType .tournament to see the list of possible subcommands.\nPvE dungeon tournament administration.'),
('tournament create', 'Syntax: .tournament create "$name" [normal|heroic]\nCreates a tournament in draft state (default difficulty: heroic, default item level cap: 213).'),
('tournament delete', 'Syntax: .tournament delete $tournamentId\nDeletes a tournament including its teams, members and dungeon selection. Live runs are voided.'),
('tournament state', 'Syntax: .tournament state $tournamentId $state\nSets the tournament state: draft | registration | locked | running | ended.\nOnly one tournament may be running, transitioning to running reveals the dungeon selection, leaving running voids live runs.'),
('tournament ilvl', 'Syntax: .tournament ilvl $tournamentId $cap\nSets the maximum allowed equipped item level for contestants.'),
('tournament status', 'Syntax: .tournament status [$tournamentId]\nShows state, difficulty, item level cap, dungeon selection and team count of the given (or active) tournament.'),
('tournament standings', 'Syntax: .tournament standings [$tournamentId]\nShows the scoreboard: points, completed dungeons and combined time per team.'),
('tournament dungeon', 'Syntax: .tournament dungeon $subcommand\nTournament dungeon selection management.'),
('tournament dungeon set', 'Syntax: .tournament dungeon set $tournamentId $slot $mapId [normal|heroic]\nAssigns a 5-player dungeon to a selection slot (1-5). Duplicates are rejected, redefining a slot voids its live runs.\nDungeons stay hidden until the tournament is running.'),
('tournament dungeon remove', 'Syntax: .tournament dungeon remove $tournamentId $slot\nClears a dungeon selection slot. Live runs of the slot are voided.'),
('tournament team', 'Syntax: .tournament team $subcommand\nTournament team management.'),
('tournament team create', 'Syntax: .tournament team create $tournamentId "$name"\nRegisters a new team to the tournament.'),
('tournament team delete', 'Syntax: .tournament team delete $teamId\nDeletes a team and its members. Live runs are voided.'),
('tournament team info', 'Syntax: .tournament team info $teamId\nShows the team status and roster, warns when the 1 tank / 1 healer / 3 dps composition is not met.'),
('tournament team list', 'Syntax: .tournament team list [$tournamentId]\nLists the teams of the given (or active) tournament.'),
('tournament team disqualify', 'Syntax: .tournament team disqualify $teamId $reason\nDisqualifies a team from competing. Live runs are voided, completed runs stop counting for the standings.'),
('tournament team requalify', 'Syntax: .tournament team requalify $teamId\nLifts the disqualification of a team.'),
('tournament team member', 'Syntax: .tournament team member $subcommand\nTournament team roster management.'),
('tournament team member add', 'Syntax: .tournament team member add $teamId $characterName tank|healer|dps\nAdds a character to the team roster (works for offline characters). A character may only belong to one team per tournament.'),
('tournament team member remove', 'Syntax: .tournament team member remove $teamId $characterName\nRemoves a character from the team roster.'),
('tournament run', 'Syntax: .tournament run $subcommand\nTournament run tracking and verdicts.'),
('tournament run list', 'Syntax: .tournament run list $teamId\nShows the stored run history of a team with states, times and reasons.'),
('tournament run live', 'Syntax: .tournament run live\nShows all runs currently in flight with their elapsed times.'),
('tournament run start', 'Syntax: .tournament run start $teamId\nManually starts a run for a team standing inside a fresh tournament dungeon. The instance may only contain registered members within the gear cap.'),
('tournament run reject', 'Syntax: .tournament run reject $runId $reason\nRejects a run (rule violation). Works on live and stored runs.'),
('tournament run void', 'Syntax: .tournament run void $runId $reason\nVoids a run without fault. Works on live and stored runs.');
